### ISSUE TITLE
v1.0.14 Integration Startup failure due to timeout

### ISSUE THREAD

**Issue by PsychoV3** [JohNan/homeassistant-wellbeing#78] opened 2024-02-04 11:42 UTC
Been fine for literally ever for me (great work), until the last few days where I get timeout upo integration start.

I have reloadd, redownloaded, deleted and reinstalled (tried 1.0.13 too) but still the same error:

2024-02-01 08:45:39.070 ERROR (MainThread) [custom_components.wellbeing] Timeout error fetching information from https://api.ocp.electrolux.one/appliance/api/v2/appliances

**Comment by ryssel** [comment] 2024-02-04 12:26
Mine stopped working today.
I updated to 1.0.14 tried to go back to 1.0.12 but same problem.

	Line 128: 2024-02-04 13:18:56.760 INFO (MainThread) [homeassistant.setup] Setting up wellbeing
	Line 129: 2024-02-04 13:18:56.760 INFO (MainThread) [homeassistant.setup] Setup of domain wellbeing took 0.0 seconds
	Line 897: 2024-02-04 13:23:01.391 DEBUG (MainThread) [custom_components.wellbeing] Current token is not set or expired
	Line 898: 2024-02-04 13:23:01.902 DEBUG (MainThread) [custom_components.wellbeing] Received new token sucssfully
	Line 899: 2024-02-04 13:23:01.928 DEBUG (MainThread) [custom_components.wellbeing] Fetched data: None
	Line 900: 2024-02-04 13:23:01.929 DEBUG (MainThread) [custom_components.wellbeing] Finished fetching wellbeing data in 0.026 seconds (success: False)

**Comment by modo1302** [comment] 2024-02-04 12:31
same here!

**Comment by WouterNordsiek** [comment] 2024-02-04 12:33
Same here. https://github.com/JohNan/homeassistant-wellbeing/issues/76#issuecomment-1925643788

**Comment by Zwoet** [comment] 2024-02-04 13:43
Got the same issue since last HA update.

**Comment by Uffe78** [comment] 2024-02-04 17:06
Samma här den slutade funka igår för mig.
Privat att uppdatera till 1.14 men hjälper inte tyvärr.

**Comment by patrikjohansson87** [comment] 2024-02-04 17:16
Same problem for me

**Comment by Lucus123** [comment] 2024-02-04 19:02
Same problem here, something changed in the way the API is handled within Home Assistant it seems

**Comment by zox-gh** [comment] 2024-02-04 21:15
Same for me. Since 2 days ago, integration stopped working, reporting failure.

**Comment by jgjestad** [comment] 2024-02-05 19:08
Same for me, stopped working. Have not tried downgrading, will wait for a fix :)

**Comment by foekpham** [comment] 2024-02-05 19:11
Downgrading did the job for me.

**Comment by nabil121212** [comment] 2024-02-05 22:42
Downgrading to 2024.1.5 worked.
I used the command-   ha core update --version 2024.1.5

**Comment by JohNan** [comment] 2024-02-05 23:07
thank you. this is great information. I saw that they bumped `aiohttp` in `2024.1.6` and I wonder if that is the cause. I'm currently looking into is.

**Comment by JohNan** [comment] 2024-02-05 23:50
I just tried the integration in my dev environment and it runs without issues. It is however the latest from the dev branch. Maybe they have done some changes that made it work again.

When checking out `2024.1.6` in my dev environment i don't get any data. Content-Length of the returned data is 0. I cannot find any reason why.

So my suggestion is to either revert back to `2024.1.5` or wait for `2024.2.x`

**Comment by zox-gh** [comment] 2024-02-06 00:37
I confirm downgrade to 2024.1.5 worked for me too.

**Comment by PsychoV3** [comment] 2024-02-06 17:42
Can also confirm downgrade to 2024.5 worked. Thanks :)

**Comment by AWahlqvist** [comment] 2024-02-07 21:39
I can confirm it works again with 2024.2.0! Thanks!

**Comment by WouterNordsiek** [comment] 2024-02-07 23:01
Same here, it does work again with 2024.2! Thanks

**Comment by modo1302** [comment] 2024-02-08 08:11
hey, for me still something's wrong. The purifyer entities become unavailable every couple of minutes, then come back online, then offline again
![image](https://github.com/JohNan/homeassistant-wellbeing/assets/133964285/305f8f53-fc97-419d-80c1-1c068f30e75d)

**Comment by patrikjohansson87** [comment] 2024-02-08 11:08
> hey, for me still something's wrong. The purifyer entities become unavailable every couple of minutes, then come back online for several seconds, then offline again ![image](https://private-user-images.githubusercontent.com/133964285/303256056-305f8f53-fc97-419d-80c1-1c068f30e75d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTA2NTAsIm5iZiI6MTcwNzM5MDM1MCwicGF0aCI6Ii8xMzM5NjQyODUvMzAzMjU2MDU2LTMwNWY4ZjUzLWZjOTctNDE5ZC04MGMxLTFjMDY4ZjMwZTc1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQxMTA1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWFmNzhlYTcyNWYwN2I4YjhkMDE5MzVlZmQ0ZmIxZmU4MDVjNDE0NmQ4NThjNDE3MjRlOGQzMjM0ZjVkMzQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tiFMtLQFh3DG1zV2h4RxE7A767Kv6lqapsR4jj8MMgo) ![image](https://private-user-images.githubusercontent.com/133964285/303257598-ea8c6e65-d62c-4129-921b-7358ff66d38b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTA2NTAsIm5iZiI6MTcwNzM5MDM1MCwicGF0aCI6Ii8xMzM5NjQyODUvMzAzMjU3NTk4LWVhOGM2ZTY1LWQ2MmMtNDEyOS05MjFiLTczNThmZjY2ZDM4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQxMTA1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjMxN2U5NWYyMjllNmQwZjgzNmExODdiZDgwNzIwMDMyZTcwNzIxZGY2ZGMzZmVlNTQ4NGM4MjRlMzFkNmI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QdXhnOZ6joDIXgeKSn31wAhka4RgV3Z6PFmgPQhkoG4)


I’m experiencing the same behavior. When reloading the integration, it works for ~30 seconds and then turns to unavailable

**Comment by AWahlqvist** [comment] 2024-02-08 11:21
It worked flawlessly for me for a couple of hours, but it suddenly became more unstable after a while.

<img width="262" alt="image" src="https://github.com/JohNan/homeassistant-wellbeing/assets/5821559/0bb21064-7278-48d0-b259-1c9f6d66e662">

I see some errors in the debug log:
2024-02-07 22:35:33.396 ERROR (MainThread) [custom_components.wellbeing] Timeout error fetching information from https://api.ocp.electrolux.one/one-account-authorization/api/v1/token - 
2024-02-07 22:35:33.397 ERROR (MainThread) [custom_components.wellbeing] AccessToken 1 is missing
2024-02-08 03:59:46.836 ERROR (MainThread) [custom_components.wellbeing] Error fetching wellbeing data: 

I wonder if the API just became unstable (bad timing with the update...) or if  it's something else? Anyone still on 2024.1.5 that can confirm it works with the previous version?

**Comment by PsychoV3** [comment] 2024-02-08 12:39
Yes I have now noted the integration on either 2024.1.5, or 2024.2.0 is having the behaviours of "unavailable" and "working" frequently.

**Comment by priwi** [comment] 2024-02-08 19:33
I downgraded to 2024.1.5 and it works for 6 hours without any issue.

**Comment by rrataj** [comment] 2024-02-09 15:15
I can confirm it works fine with 2024.2.1 since update (2h ago)
![Zrzut ekranu 2024-02-9 o 16 14 18](https://github.com/JohNan/homeassistant-wellbeing/assets/6181239/ac857059-3d32-4940-8da4-fc0c5bb1e285)

**Comment by JohNan** [comment] 2024-02-09 16:17
Thanks for all the info. I wonder if the problem might be in the API after all. Maybe they have added some kind of rate limits.

When I was debugging the request and response the content was empty, which make me believe it is the API rather than HA. The strange thing is that it seems to work the first time after an upgrade/downgrade. Maybe because it take some time between the polling.

I will look into increasing the poll time to see if it helps.

**Comment by PsychoV3** [comment] 2024-02-09 16:45
> I can confirm it works fine with 2024.2.1 since update (2h ago) ![Zrzut ekranu 2024-02-9 o 16 14 18](https://private-user-images.githubusercontent.com/6181239/303693534-ac857059-3d32-4940-8da4-fc0c5bb1e285.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0OTI0NTcsIm5iZiI6MTcwNzQ5MjE1NywicGF0aCI6Ii82MTgxMjM5LzMwMzY5MzUzNC1hYzg1NzA1OS0zZDMyLTQ5NDAtOGRhNC1mYzBjNWJiMWUyODUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDlUMTUyMjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzY1NGFkZDU0ODljNGIzOTc2ZWVhYWUzM2MwOTZmNDZjNGU3Mjg1YTU1ODJjZjNkNjNiODc4NjAwMzYxMzE3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1ZDbG_fRFuMK_y1BFKp21at0UzhxWIlC1W-DbhsolOY)

Yes my entities look like this now too, look as though the 2024.2.1 update has resolved the issue.

**Comment by modo1302** [comment] 2024-02-09 21:59
are you guys serious? again, issue is not fixed!
![image](https://github.com/JohNan/homeassistant-wellbeing/assets/133964285/6be17f4b-be4f-4452-92aa-ebbc1612d372)

**Comment by PsychoV3** [comment] 2024-02-10 09:26
> are you guys serious? again, issue is not fixed in 2024.2.1! ![image](https://private-user-images.githubusercontent.com/133964285/303785855-6be17f4b-be4f-4452-92aa-ebbc1612d372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTc0MzksIm5iZiI6MTcwNzU1NzEzOSwicGF0aCI6Ii8xMzM5NjQyODUvMzAzNzg1ODU1LTZiZTE3ZjRiLWJlNGYtNDQ1Mi05MmFhLWViYmMxNjEyZDM3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQwOTI1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2U4ZGMwNjFhNjJkODY4YWVlMjVlNTU4ZDRlYTc1MTI5OWUwODAxMTg1Y2M0NTU2MDIwY2VhOTFlNzIxYTFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K5HcKl82tCK4y3CJDNSrAY4kLF2wUXAYPmSY7W6tEy4)

It would appear the initial analysis was a little premature, it is intermittent again but not as bad as previously,.

**Comment by Zwoet** [comment] 2024-02-10 12:08
Just did the update and intergration is working and devices back as entities. Hopes it stays working!

![image](https://github.com/JohNan/homeassistant-wellbeing/assets/51120687/57e31f71-b91b-4415-a4d5-252f17e74314)

**Comment by olanystrom** [comment] 2024-02-11 12:02
Can it be because the aiohttp.ClientSession is configured with async_get_clientsession during init, and not fetched from hass-object during every sync-period ?
I can rewrite the WellbeingApiClient to fetch the session from hass-object instead of being given the session from init.

**Comment by JohNan** [comment] 2024-02-11 15:07
> Can it be because the aiohttp.ClientSession is configured with async_get_clientsession during init, and not fetched from hass-object during every sync-period ?
> I can rewrite the WellbeingApiClient to fetch the session from hass-object instead of being given the session from init.

Might be! At least it's worth a try. Push a PR and I'll approve it!

**Comment by olanystrom** [comment] 2024-02-11 20:35
It does not seem like became better.
Still
2024-02-11 21:34:16.466 DEBUG (MainThread) [custom_components.wellbeing] Current token is not set or expired
2024-02-11 21:34:17.078 DEBUG (MainThread) [custom_components.wellbeing] Received new token sucssfully
2024-02-11 21:34:17.104 DEBUG (MainThread) [custom_components.wellbeing] Fetched data: None
2024-02-11 21:34:17.105 DEBUG (MainThread) [custom_components.wellbeing] Finished fetching wellbeing data in 0.026 seconds (success: False)

**Comment by olanystrom** [comment] 2024-02-12 10:45
I seem to get http-status 429 (Too Many requests) on many requests from HA.

**Comment by olanystrom** [comment] 2024-02-12 12:12
If I change User-Agent we get the data no problem, but if we send with default User-agent we get blocked with HTTP/429 Too Many requests

**Comment by olanystrom** [comment] 2024-02-12 12:30
@JohNan do you have any contact with Electrolux so we can talk to their API-team about this?

**Comment by JohNan** [comment] 2024-02-12 13:59
> @JohNan do you have any contact with Electrolux so we can talk to their API-team about this?

Unfortunately not. Maybe @androidand has some contacts?

**Comment by JohNan** [comment] 2024-02-12 14:04
We are all also using the same API key and client secret since it is hard coded and extracted from the app. What if we change to use the same User-Agent as the app does?

**Comment by olanystrom** [comment] 2024-02-12 14:06
I'm using

> User-Agent: HomeAssistant/WellBeing

for my install at home. That works really good right now.

**Comment by JohNan** [comment] 2024-02-12 14:24
This is the User-Agent the app uses: https://github.com/JohNan/homeassistant-wellbeing/pull/84/files#diff-3da8c1a6ea10e2885c00e772ec540f7756569f6a13e8186b5acb9ddc3ff56439R24

Let's see how it works out.

**Comment by rrataj** [comment] 2024-02-12 14:32
Great, thanks! That works, let's see how long.

**Comment by PsychoV3** [comment] 2024-02-12 14:56
> This is the User-Agent the app uses: https://github.com/JohNan/homeassistant-wellbeing/pull/84/files#diff-3da8c1a6ea10e2885c00e772ec540f7756569f6a13e8186b5acb9ddc3ff56439R24
> 
> Let's see how it works out. New release available

Installing now, will revert with news :)

**Comment by Zwoet** [comment] 2024-02-12 15:02
Just updated, everything online again! Thanks guys for all the work!

**Comment by foekpham** [comment] 2024-02-12 15:05
Its working again! Thanks!

**Comment by PsychoV3** [comment] 2024-02-12 18:14
Since 14:57 time of upgrade it appears to have been rock solid:

<img width="556" alt="image" src="https://github.com/JohNan/homeassistant-wellbeing/assets/98703357/f00b4815-fd8c-4d07-894b-04a2e2647cc1">

**Comment by JohNan** [comment] 2024-02-12 19:10
Good to hear that it is working again! 

Let's keep the issue open until tomorrow.

**Comment by PsychoV3** [comment] 2024-02-13 09:01
To add:  

<img width="564" alt="image" src="https://github.com/JohNan/homeassistant-wellbeing/assets/98703357/bf497200-e824-443e-a533-6217d347eb03">

Great work :)

**Comment by JohNan** [comment] 2024-02-13 21:35
Closing this issue now, and let's hope it will keep working 😊

**Closed by JohNan** 2024-02-13 21:35 UTC
